// All 22 Official 8th Schedule Languages of India + Widely Spoken Regional & BRICS Languages
export const ALL_LANGUAGES = [
  // National & Popular
  { code: 'hi-IN', name: 'Hindi', native: 'हिंदी', script: 'नमस्ते', region: 'National / North', popular: true },
  { code: 'en-IN', name: 'English', native: 'English', script: 'Welcome', region: 'National / Pan-India', popular: true },
  { code: 'mr-IN', name: 'Marathi', native: 'मराठी', script: 'नमस्कार', region: 'West (Maharashtra)', popular: true },
  { code: 'bn-IN', name: 'Bengali', native: 'বাংলা', script: 'নমস্কার', region: 'East (West Bengal / Tripura)', popular: true },
  { code: 'ta-IN', name: 'Tamil', native: 'தமிழ்', script: 'வணக்கம்', region: 'South (Tamil Nadu / Puducherry)', popular: true },
  { code: 'te-IN', name: 'Telugu', native: 'తెలుగు', script: 'నమస్కారం', region: 'South (Andhra Pradesh / Telangana)', popular: true },
  
  // West India
  { code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી', script: 'નમસ્તે', region: 'West (Gujarat)' },
  { code: 'kok-IN', name: 'Konkani', native: 'कोंकणी', script: 'देव बरें करूं', region: 'West (Goa / Coastal)' },
  { code: 'sd-IN', name: 'Sindhi', native: 'سنڌي / सिन्धी', script: 'آداﺏ / नमस्कार', region: 'West / Pan-India' },
  
  // South India
  { code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ', script: 'ನಮಸ್ಕಾರ', region: 'South (Karnataka)', popular: true },
  { code: 'ml-IN', name: 'Malayalam', native: 'മലയാളം', script: 'നമസ്കാരം', region: 'South (Kerala / Lakshadweep)', popular: true },
  
  // North & Central India
  { code: 'pa-IN', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', script: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ', region: 'North (Punjab / Delhi)', popular: true },
  { code: 'ur-IN', name: 'Urdu', native: 'اردو', script: 'آداب', region: 'North / Pan-India' },
  { code: 'ks-IN', name: 'Kashmiri', native: 'کٲشُر / कश्मीरी', script: 'سلام / नमस्कार', region: 'North (Jammu & Kashmir)' },
  { code: 'doi-IN', name: 'Dogri', native: 'डोगरी', script: 'नमस्कार', region: 'North (Jammu)' },
  { code: 'sa-IN', name: 'Sanskrit', native: 'संस्कृतम्', script: 'नमो नमः', region: 'National / Classical' },
  
  // East & North-East India
  { code: 'or-IN', name: 'Odia', native: 'ଓଡ଼ିଆ', script: 'ନମସ୍କାର', region: 'East (Odisha)', popular: true },
  { code: 'as-IN', name: 'Assamese', native: 'অসমীয়া', script: 'নমস্কাৰ', region: 'North-East (Assam)', popular: true },
  { code: 'mai-IN', name: 'Maithili', native: 'मैथिली', script: 'प्रणाम', region: 'East (Bihar / Mithila)' },
  { code: 'bho-IN', name: 'Bhojpuri', native: 'भोजपुरी', script: 'प्रणाम', region: 'East (Bihar / UP)' },
  { code: 'sat-IN', name: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ', script: 'ᱡᱚᱦᱟᱨ', region: 'East (Jharkhand / Odisha)' },
  { code: 'mni-IN', name: 'Manipuri (Meitei)', native: 'মৈতৈলোন্ / ꯃꯤꯇꯩꯂꯣꯟ', script: 'ꯈꯨꯔꯨꯝꯖꯔꯤ', region: 'North-East (Manipur)' },
  { code: 'brx-IN', name: 'Bodo', native: 'बर’', script: 'खुलुमबाय', region: 'North-East (Assam / Bodoland)' },
  { code: 'ne-IN', name: 'Nepali', native: 'नेपाली', script: 'नमस्ते', region: 'North-East (Sikkim / Gorkha)' },

  // BRICS Partner Nations (For Global Scalability Pitch)
  { code: 'pt-BR', name: 'Portuguese', native: 'Português', script: 'Olá (BRICS)', region: 'BRICS - Brazil', brics: true },
  { code: 'ru-RU', name: 'Russian', native: 'Русский', script: 'Привет (BRICS)', region: 'BRICS - Russia', brics: true },
  { code: 'zh-CN', name: 'Chinese', native: '中文', script: '你好 (BRICS)', region: 'BRICS - China', brics: true },
  { code: 'zu-ZA', name: 'isiZulu', native: 'isiZulu', script: 'Sawubona (BRICS)', region: 'BRICS - South Africa', brics: true }
];

export const LANGUAGE_REGIONS = [
  { id: 'all', label: 'All Languages' },
  { id: 'popular', label: 'Most Popular' },
  { id: 'north', label: 'North & Central' },
  { id: 'south', label: 'South India' },
  { id: 'west', label: 'West India' },
  { id: 'east', label: 'East & North-East' },
  { id: 'brics', label: 'BRICS Nations' }
];

// Comprehensive State to District Data Mapping
export const STATES_AND_DISTRICTS = {
  'Maharashtra': ['Pune', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nashik', 'Chhatrapati Sambhaji Nagar', 'Thane', 'Kolhapur', 'Solapur', 'Amravati', 'Nanded', 'Satara', 'Sangli', 'Ahmednagar', 'Jalgaon', 'Latur', 'Dhule'],
  'Bihar': ['Patna', 'Purnia', 'Gaya', 'Muzaffarpur', 'Bhagalpur', 'Darbhanga', 'Begusarai', 'Katihar', 'Samastipur', 'Nalanda', 'Saharsa', 'Madhubani', 'Rohtas', 'Vaishali', 'Saran', 'Siwan', 'East Champaran'],
  'Uttar Pradesh': ['Lucknow', 'Varanasi', 'Kanpur Nagar', 'Agra', 'Prayagraj', 'Noida (Gautam Buddha Nagar)', 'Ghaziabad', 'Gorakhpur', 'Meerut', 'Bareilly', 'Aligarh', 'Moradabad', 'Ayodhya', 'Jhansi'],
  'Tamil Nadu': ['Chennai', 'Madurai', 'Coimbatore', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Erode', 'Vellore', 'Thanjavur', 'Dindigul', 'Kanchipuram', 'Cuddalore', 'Tiruvannamalai'],
  'Karnataka': ['Bengaluru Urban', 'Bengaluru Rural', 'Mysuru', 'Hubballi-Dharwad', 'Mangaluru (Dakshina Kannada)', 'Belagavi', 'Kalaburagi', 'Ballari', 'Shivamogga', 'Tumakuru', 'Udupi', 'Davanagere'],
  'West Bengal': ['Kolkata', 'North 24 Parganas', 'South 24 Parganas', 'Howrah', 'Hooghly', 'Purba Medinipur', 'Darjeeling', 'Siliguri', 'Murshidabad', 'Nadia', 'Paschim Bardhaman'],
  'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Gandhinagar', 'Junagadh', 'Kutch', 'Anand', 'Mehsana', 'Bharuch'],
  'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada (NTR)', 'Guntur', 'Tirupati', 'Kurnool', 'Nellore', 'Kakinada', 'Kadapa', 'Anantapur', 'Rajahmundry'],
  'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Karimnagar', 'Khammam', 'Rangareddy', 'Medchal-Malkajgiri', 'Nalgonda', 'Mahabubnagar'],
  'Kerala': ['Thiruvananthapuram', 'Ernakulam (Kochi)', 'Kozhikode', 'Thrissur', 'Kollam', 'Palakkad', 'Kannur', 'Alappuzha', 'Kottayam', 'Malappuram'],
  'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Bhilwara', 'Alwar', 'Sikar', 'Pali', 'Bharatpur'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain', 'Sagar', 'Rewa', 'Satna', 'Ratlam'],
  'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Mohali (SAS Nagar)', 'Hoshiarpur', 'Pathankot'],
  'Haryana': ['Gurugram', 'Faridabad', 'Panipat', 'Ambala', 'Karnal', 'Hisar', 'Rohtak', 'Sonipat', 'Panchkula'],
  'Odisha': ['Bhubaneswar (Khurda)', 'Cuttack', 'Rourkela (Sundargarh)', 'Puri', 'Sambalpur', 'Berhampur (Ganjam)', 'Balasore'],
  'Assam': ['Guwahati (Kamrup Metro)', 'Dibrugarh', 'Silchar (Cachar)', 'Jorhat', 'Nagaon', 'Tezpur (Sonitpur)', 'Tinsukia'],
  'Jharkhand': ['Ranchi', 'Jamshedpur (East Singhbhum)', 'Dhanbad', 'Bokaro', 'Hazaribagh', 'Deoghar', 'Giridih'],
  'Chhattisgarh': ['Raipur', 'Bhilai (Durg)', 'Bilaspur', 'Korba', 'Rajnandgaon', 'Jagdalpur (Bastar)'],
  'Uttarakhand': ['Dehradun', 'Haridwar', 'Nainital', 'Rishikesh', 'Udham Singh Nagar', 'Roorkee', 'Almora'],
  'Himachal Pradesh': ['Shimla', 'Dharamshala (Kangra)', 'Mandi', 'Solan', 'Kullu', 'Hamirpur'],
  'Goa': ['North Goa (Panaji)', 'South Goa (Margao)'],
  'Jammu & Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Udhampur', 'Kathua'],
  'Tripura': ['Agartala (West Tripura)', 'Gomati', 'Dhalai', 'Unakoti'],
  'Meghalaya': ['Shillong (East Khasi Hills)', 'Tura (West Garo Hills)', 'Jowai'],
  'Manipur': ['Imphal West', 'Imphal East', 'Churachandpur', 'Thoubal'],
  'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung'],
  'Mizoram': ['Aizawl', 'Lunglei', 'Champhai'],
  'Sikkim': ['Gangtok', 'Namchi', 'Gyalshing'],
  'Arunachal Pradesh': ['Itanagar (Papum Pare)', 'Tawang', 'Pasighat'],
  'Delhi (NCT)': ['New Delhi', 'Central Delhi', 'South Delhi', 'North Delhi', 'East Delhi', 'West Delhi'],
  'Puducherry': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  'Chandigarh': ['Chandigarh'],
  'Ladakh': ['Leh', 'Kargil'],
  'BRICS - Brazil': ['São Paulo', 'Rio de Janeiro', 'Brasília', 'Belo Horizonte', 'Salvador'],
  'BRICS - South Africa': ['Johannesburg (Gauteng)', 'Cape Town (Western Cape)', 'Durban (KwaZulu-Natal)', 'Pretoria']
};

// Fast Pincode Auto-Detection Database (Indian Postal System 1st & 2nd digit routing)
export const PINCODE_MAP = {
  '11': { state: 'Delhi (NCT)', district: 'New Delhi', areaType: 'urban' },
  '12': { state: 'Haryana', district: 'Gurugram', areaType: 'urban' },
  '13': { state: 'Haryana', district: 'Ambala', areaType: 'rural' },
  '14': { state: 'Punjab', district: 'Ludhiana', areaType: 'urban' },
  '15': { state: 'Punjab', district: 'Bathinda', areaType: 'rural' },
  '16': { state: 'Chandigarh', district: 'Chandigarh', areaType: 'urban' },
  '17': { state: 'Himachal Pradesh', district: 'Shimla', areaType: 'rural' },
  '18': { state: 'Jammu & Kashmir', district: 'Jammu', areaType: 'urban' },
  '19': { state: 'Jammu & Kashmir', district: 'Srinagar', areaType: 'urban' },
  '20': { state: 'Uttar Pradesh', district: 'Aligarh', areaType: 'rural' },
  '21': { state: 'Uttar Pradesh', district: 'Prayagraj', areaType: 'rural' },
  '22': { state: 'Uttar Pradesh', district: 'Lucknow', areaType: 'urban' },
  '24': { state: 'Uttarakhand', district: 'Dehradun', areaType: 'urban' },
  '28': { state: 'Uttar Pradesh', district: 'Agra', areaType: 'urban' },
  '30': { state: 'Rajasthan', district: 'Jaipur', areaType: 'urban' },
  '31': { state: 'Rajasthan', district: 'Udaipur', areaType: 'rural' },
  '38': { state: 'Gujarat', district: 'Ahmedabad', areaType: 'urban' },
  '39': { state: 'Gujarat', district: 'Surat', areaType: 'urban' },
  '40': { state: 'Maharashtra', district: 'Mumbai City', areaType: 'urban' },
  '41': { state: 'Maharashtra', district: 'Pune', areaType: 'rural' },
  '42': { state: 'Maharashtra', district: 'Nashik', areaType: 'rural' },
  '43': { state: 'Maharashtra', district: 'Chhatrapati Sambhaji Nagar', areaType: 'rural' },
  '44': { state: 'Maharashtra', district: 'Nagpur', areaType: 'urban' },
  '46': { state: 'Madhya Pradesh', district: 'Bhopal', areaType: 'urban' },
  '45': { state: 'Madhya Pradesh', district: 'Indore', areaType: 'urban' },
  '50': { state: 'Telangana', district: 'Hyderabad', areaType: 'urban' },
  '51': { state: 'Andhra Pradesh', district: 'Tirupati', areaType: 'rural' },
  '53': { state: 'Andhra Pradesh', district: 'Visakhapatnam', areaType: 'urban' },
  '56': { state: 'Karnataka', district: 'Bengaluru Urban', areaType: 'urban' },
  '57': { state: 'Karnataka', district: 'Mangaluru (Dakshina Kannada)', areaType: 'rural' },
  '58': { state: 'Karnataka', district: 'Hubballi-Dharwad', areaType: 'rural' },
  '60': { state: 'Tamil Nadu', district: 'Chennai', areaType: 'urban' },
  '62': { state: 'Tamil Nadu', district: 'Madurai', areaType: 'rural' },
  '64': { state: 'Tamil Nadu', district: 'Coimbatore', areaType: 'urban' },
  '67': { state: 'Kerala', district: 'Kozhikode', areaType: 'rural' },
  '68': { state: 'Kerala', district: 'Ernakulam (Kochi)', areaType: 'urban' },
  '69': { state: 'Kerala', district: 'Thiruvananthapuram', areaType: 'urban' },
  '70': { state: 'West Bengal', district: 'Kolkata', areaType: 'urban' },
  '71': { state: 'West Bengal', district: 'Howrah', areaType: 'urban' },
  '72': { state: 'West Bengal', district: 'Purba Medinipur', areaType: 'rural' },
  '73': { state: 'West Bengal', district: 'Siliguri', areaType: 'rural' },
  '75': { state: 'Odisha', district: 'Bhubaneswar (Khurda)', areaType: 'urban' },
  '76': { state: 'Odisha', district: 'Cuttack', areaType: 'rural' },
  '78': { state: 'Assam', district: 'Guwahati (Kamrup Metro)', areaType: 'urban' },
  '79': { state: 'Meghalaya', district: 'Shillong (East Khasi Hills)', areaType: 'rural' },
  '80': { state: 'Bihar', district: 'Patna', areaType: 'urban' },
  '81': { state: 'Bihar', district: 'Bhagalpur', areaType: 'rural' },
  '82': { state: 'Jharkhand', district: 'Ranchi', areaType: 'urban' },
  '84': { state: 'Bihar', district: 'Muzaffarpur', areaType: 'rural' },
  '85': { state: 'Bihar', district: 'Purnia', areaType: 'rural' }
};

// Rich Demo Presets Across India & BRICS for Hackathon Presentation
export const EXPANDED_DEMO_CITIZENS = [
  {
    fullName: 'राकेश कुमार (Rakesh Kumar)',
    mobile: '9876543210',
    email: 'rakesh.kumar@bihar.gov.in',
    state: 'Bihar',
    district: 'Purnia',
    areaType: 'rural',
    tehsil: 'Kasba Block (कस्बा प्रखंड)',
    panchayatOrWard: 'Srinagar Gram Panchayat (श्रीनगर पंचायत)',
    pincode: '854301',
    language: 'hi-IN',
    officialRouting: 'BDO Kasba & DM Purnia',
    povertyIndexFactor: 'High (0.84 - Rural Priority Boost)'
  },
  {
    fullName: 'सचिन पाटील (Sachin Patil)',
    mobile: '9822012345',
    email: 'sachin.patil@pune.gov.in',
    state: 'Maharashtra',
    district: 'Pune',
    areaType: 'rural',
    tehsil: 'Haveli Taluka (हवेली तालुका)',
    panchayatOrWard: 'Wagholi Gram Panchayat (वाघोली)',
    pincode: '412207',
    language: 'mr-IN',
    officialRouting: 'BDO Haveli & Collector Pune',
    povertyIndexFactor: 'Developing (0.52)'
  },
  {
    fullName: 'Meenakshi Sundaram',
    mobile: '9840198765',
    email: 'meenakshi.s@chennaicorp.gov.in',
    state: 'Tamil Nadu',
    district: 'Chennai',
    areaType: 'urban',
    tehsil: 'Mylapore Zone',
    panchayatOrWard: 'Ward No. 124 (Alwarpet)',
    pincode: '600004',
    language: 'ta-IN',
    officialRouting: 'Zonal Officer & Commissioner GCC',
    povertyIndexFactor: 'Urban Baseline (0.28)'
  },
  {
    fullName: 'গৌরব মুখার্জী (Gourab Mukherjee)',
    mobile: '9831098765',
    email: 'gourab.m@kolkata.gov.in',
    state: 'West Bengal',
    district: 'Kolkata',
    areaType: 'urban',
    tehsil: 'Borough VIII',
    panchayatOrWard: 'Ward No. 85 (Ballygunge)',
    pincode: '700019',
    language: 'bn-IN',
    officialRouting: 'Borough Executive & KMC Mayor',
    povertyIndexFactor: 'Urban Baseline (0.31)'
  },
  {
    fullName: 'ਹਰਪ੍ਰੀਤ ਸਿੰਘ (Harpreet Singh)',
    mobile: '9814012345',
    email: 'harpreet.singh@punjab.gov.in',
    state: 'Punjab',
    district: 'Ludhiana',
    areaType: 'rural',
    tehsil: 'Jagraon Block',
    panchayatOrWard: 'Sidhwan Bet Panchayat',
    pincode: '142025',
    language: 'pa-IN',
    officialRouting: 'BDO Jagraon & DC Ludhiana',
    povertyIndexFactor: 'Agricultural Zone (0.45)'
  },
  {
    fullName: 'Carlos Silva (BRICS Demo)',
    mobile: '+55 11 98765-4321',
    email: 'carlos.silva@gov.br',
    state: 'BRICS - Brazil',
    district: 'São Paulo',
    areaType: 'urban',
    tehsil: 'Itaquera Subprefeitura',
    panchayatOrWard: 'Distrito José Bonifácio',
    pincode: '08210-000',
    language: 'pt-BR',
    officialRouting: 'Subprefeito Itaquera & Prefeito SP',
    povertyIndexFactor: 'Developing (0.64)'
  }
];

// Hierarchical Hotspots covering National, State, District & Precise Hyper-Local Wards
export const DEFAULT_HOTSPOTS = [
  {
    id: 'JD-942108',
    title: 'Wagholi Main Conduit Rupture',
    summary: 'Critical 400mm drinking water main burst near Wagholi Gram Panchayat, affecting 14,000 residents.',
    department: 'Ministry of Jal Shakti / Water Supply Board',
    deptKey: 'jal_shakti',
    state: 'Maharashtra',
    district: 'Pune',
    tehsil: 'Haveli Taluka',
    wardOrPanchayat: 'Wagholi Gram Panchayat',
    landmark: 'Opposite Primary Health Centre, Nagar Road',
    coords: { x: -0.6, z: 0.5, lat: 18.5793, lng: 73.9814 },
    urgency: 8.9,
    baseUrgency: 7.2,
    povertyBoost: '+1.7 (Rural Deficit Weight)',
    areaType: 'Rural (Gram Panchayat)',
    routing: 'BDO Haveli, Superintending Engineer Jal Shakti & DM Pune',
    citizen: 'Sunil Deshmukh (UID: 9822998877)',
    imageVerified: true,
    imageConfidence: 97,
    status: 'Field Team Dispatched',
    timestamp: '2 mins ago',
    country: 'India'
  },
  {
    id: 'JD-942109',
    title: 'K-West Stormwater Arterial Clog',
    summary: 'High-density plastic accumulation choking subterranean drainage culvert prior to monsoon.',
    department: 'Public Works Department (PWD / MCGM)',
    deptKey: 'pwd',
    state: 'Maharashtra',
    district: 'Mumbai City',
    tehsil: 'Andheri West',
    wardOrPanchayat: 'Ward No. 64 (K-West)',
    landmark: 'SV Road Junction, near Andheri Station',
    coords: { x: -1.2, z: 0.3, lat: 19.1197, lng: 72.8468 },
    urgency: 8.4,
    baseUrgency: 7.5,
    povertyBoost: '+0.9 (Flood Vulnerability Index)',
    areaType: 'Urban (Municipal Ward)',
    routing: 'Ward Officer K-West & Chief Engineer Stormwater MCGM',
    citizen: 'Kavita Mehta (UID: 9820011223)',
    imageVerified: true,
    imageConfidence: 95,
    status: 'Work Order Generated',
    timestamp: '18 mins ago',
    country: 'India'
  },
  {
    id: 'JD-811420',
    title: 'NH-31 Arterial Bridge Fissure',
    summary: 'Critical structural shear crack detected on pillar #4 of bridge connecting Purnia to Katihar.',
    department: 'Public Works Department (PWD / NHAI)',
    deptKey: 'pwd',
    state: 'Bihar',
    district: 'Purnia',
    tehsil: 'Kasba Block',
    wardOrPanchayat: 'Kasba Rural Sector 3',
    landmark: 'Kilometer Stone 42, NH-31 Bypass',
    coords: { x: 1.4, z: -0.5, lat: 25.7771, lng: 87.4753 },
    urgency: 9.4,
    baseUrgency: 8.0,
    povertyBoost: '+1.4 (High Vulnerability Index)',
    areaType: 'Rural (Block)',
    routing: 'District Magistrate Purnia & Executive Engineer NHAI',
    citizen: 'Rameshwar Yadav (UID: 9431023456)',
    imageVerified: true,
    imageConfidence: 96,
    status: 'Traffic Diverted / Urgent Inspection',
    timestamp: '14 mins ago',
    country: 'India'
  },
  {
    id: 'JD-722105',
    title: 'Tambaram PHC Oxygen Plant Voltage Dip',
    summary: 'Substation transformer overload creating severe brownouts across neonatal intensive care units.',
    department: 'Ministry of Power & Energy',
    deptKey: 'power',
    state: 'Tamil Nadu',
    district: 'Chennai',
    tehsil: 'Tambaram Taluk',
    wardOrPanchayat: 'Zone 14, Ward 172',
    landmark: 'Government Taluk Hospital Campus',
    coords: { x: 0.2, z: 1.9, lat: 12.9249, lng: 80.1478 },
    urgency: 9.2,
    baseUrgency: 8.8,
    povertyBoost: '+0.4 (Essential Healthcare Node)',
    areaType: 'Urban (Zone 14)',
    routing: 'Zonal Health Officer & TANGEDCO Superintending Engineer',
    citizen: 'Meenakshi Sundaram (UID: 9444012345)',
    imageVerified: true,
    imageConfidence: 98,
    status: 'Emergency Backup Activated',
    timestamp: '32 mins ago',
    country: 'India'
  },
  {
    id: 'JD-510022',
    title: 'Substandard Drug Batch Alert',
    summary: 'Counterfeit cephalosporin antibiotics batch intercepted in wholesale drug warehouse.',
    department: 'Ministry of Health & Family Welfare',
    deptKey: 'health_fda',
    state: 'Delhi (NCT)',
    district: 'New Delhi',
    tehsil: 'Central Delhi',
    wardOrPanchayat: 'Ward 24, Daryaganj',
    landmark: 'Wholesale Medicine Market, Netaji Subhash Marg',
    coords: { x: 0.1, z: -1.4, lat: 28.6139, lng: 77.2090 },
    urgency: 9.5,
    baseUrgency: 9.0,
    povertyBoost: '+0.5 (Public Health Hazard)',
    areaType: 'Urban Commercial',
    routing: 'Drug Controller General & Delhi State Inspector',
    citizen: 'Dr. Vivek Malhotra (UID: 9811099887)',
    imageVerified: true,
    imageConfidence: 99,
    status: 'Seizure Notice Issued',
    timestamp: '45 mins ago',
    country: 'India'
  },
  {
    id: 'JD-942110',
    title: 'Solid Waste Pileup & Overflowing Dump',
    summary: 'Extensive municipal garbage accumulation across 400m residential lane with uncollected bio-waste for 6 days.',
    department: 'Municipal Solid Waste Management & Sanitation Dept',
    deptKey: 'sanitation_swm',
    state: 'Maharashtra',
    district: 'Pune',
    tehsil: 'Haveli Taluka',
    wardOrPanchayat: 'Wagholi Sector 4',
    landmark: 'Behind Weekly Vegetable Market',
    coords: { x: -0.4, z: 0.8, lat: 18.5810, lng: 73.9850 },
    urgency: 8.8,
    baseUrgency: 7.6,
    povertyBoost: '+1.2 (Sanitation Deficit)',
    areaType: 'Rural (Gram Panchayat)',
    routing: 'Sanitary Inspector & Gram Panchayat Secretary',
    citizen: 'Sunita Patil (UID: 9822114455)',
    imageVerified: true,
    imageConfidence: 98,
    coreDefect: 'Uncollected Municipal Solid Waste & Rotten Bio-Waste Pileup',
    affectedScope: '8,500+ residents, vegetable vendors & pedestrians',
    riskLevel: 'Dengue/Malaria vector outbreak risk & toxic airborne stench',
    duration: '6 days unaddressed',
    actionRequired: 'Deploy mechanical refuse compactor and chlorine disinfection',
    status: 'Compactor Truck Dispatched',
    timestamp: '8 mins ago',
    country: 'India'
  }
];

// Initial Resolved Records for Public Audit Ledger
export const INITIAL_RESOLVED_RECORDS = [
  {
    id: 'JD-910401',
    title: 'Substation Transformer Feeder Overload & Sparking',
    department: 'Ministry of Power & State Electricity Distribution',
    deptKey: 'power',
    state: 'Maharashtra',
    district: 'Pune',
    resolvedByRole: 'authority',
    resolvedByName: 'Er. Rajesh Deshmukh',
    officerName: 'Executive Engineer (MSEDCL Pune Zonal Circle)',
    turnaroundTime: 'Resolved in 4 hrs',
    resolutionRemarks: 'Emergency mobile substation transformer deployed and primary 11kV busbar insulator replaced. Power supply normalized.',
    budgetSpent: '₹1.8 Lakhs',
    resolvedAt: '22 Aug 2026, 11:30 AM',
    country: 'India'
  },
  {
    id: 'JD-832104',
    title: 'Arterial Stormwater Drain Choke & Road Flooding',
    department: 'Municipal Solid Waste Management & Sanitation Dept',
    deptKey: 'sanitation_swm',
    state: 'Bihar',
    district: 'Patna',
    resolvedByRole: 'citizen',
    resolvedByName: 'Anand Prakash (Local Resident)',
    turnaroundTime: 'Resolved in 18 hrs',
    rating: 5,
    resolutionRemarks: 'Municipal super-sucker vacuum machine cleared the blocked culvert. Waterlogging completely drained. Thanks for the quick response!',
    resolvedAt: '22 Aug 2026, 09:15 AM',
    country: 'India'
  }
];

